services:
  mytube:
    build: .
    ports:
      - "3332:3000"
    environment:
      - PORT=3000
    volumes:
      - ./data:/app/data
      - /mnt/nas/Videos:/app/videos
    restart: unless-stopped
